// Generated by pmgen.py from passes/pmgen/xilinx_dsp_CREG.pmg

struct xilinx_dsp_CREG_pm {
  Module *module;
  SigMap sigmap;
  std::function<void()> on_accept;
  bool setup_done;
  bool generate_mode;
  int accept_cnt;

  uint32_t rngseed;
  int rng(unsigned int n) {
    rngseed ^= rngseed << 13;
    rngseed ^= rngseed >> 17;
    rngseed ^= rngseed << 5;
    return rngseed % n;
  }

  typedef std::tuple<> index_0_key_type;
  typedef std::tuple<Cell*> index_0_value_type;
  dict<index_0_key_type, vector<index_0_value_type>> index_0;
  typedef std::tuple<SigBit> index_6_key_type;
  typedef std::tuple<Cell*, int> index_6_value_type;
  dict<index_6_key_type, vector<index_6_value_type>> index_6;
  typedef std::tuple<SigSpec> index_8_key_type;
  typedef std::tuple<Cell*, IdString, bool> index_8_value_type;
  dict<index_8_key_type, vector<index_8_value_type>> index_8;
  typedef std::tuple<SigSpec, SigSpec> index_10_key_type;
  typedef std::tuple<Cell*, IdString, bool> index_10_value_type;
  dict<index_10_key_type, vector<index_10_value_type>> index_10;
  dict<SigBit, pool<Cell*>> sigusers;
  pool<Cell*> blacklist_cells;
  pool<Cell*> autoremove_cells;
  dict<Cell*,int> rollback_cache;
  int rollback;

  struct state_xilinx_dsp_packC_t {
    SigSpec argD;
    SigSpec argQ;
    SigBit clock;
    Cell* dsp;
    Cell* ff;
    Cell* ffC;
    Cell* ffCcemux;
    bool ffCcepol;
    Cell* ffCrstmux;
    bool ffCrstpol;
    Cell* ffcemux;
    bool ffcepol;
    int ffoffset;
    Cell* ffrstmux;
    bool ffrstpol;
    SigSpec sigC;
    SigSpec sigP;
  } st_xilinx_dsp_packC;

  struct udata_xilinx_dsp_packC_t {
    Cell* dff;
    SigSpec dffD;
    SigSpec dffQ;
    Cell* dffcemux;
    bool dffcepol;
    SigBit dffclock;
    Cell* dffrstmux;
    bool dffrstpol;
    std::function<SigSpec(const SigSpec&)> unextend;
  } ud_xilinx_dsp_packC;

  IdString id_b_A{"\\A"};
  IdString id_b_B{"\\B"};
  IdString id_b_C{"\\C"};
  IdString id_b_CLK{"\\CLK"};
  IdString id_b_CLK_POLARITY{"\\CLK_POLARITY"};
  IdString id_b_CREG{"\\CREG"};
  IdString id_b_D{"\\D"};
  IdString id_b_DSP48A{"\\DSP48A"};
  IdString id_b_DSP48A1{"\\DSP48A1"};
  IdString id_b_DSP48E1{"\\DSP48E1"};
  IdString id_b_P{"\\P"};
  IdString id_b_Q{"\\Q"};
  IdString id_b_USE_MULT{"\\USE_MULT"};
  IdString id_b_Y{"\\Y"};
  IdString id_b_init{"\\init"};
  IdString id_b_keep{"\\keep"};
  IdString id_d_dff{"$dff"};
  IdString id_d_mux{"$mux"};

  void add_siguser(const SigSpec &sig, Cell *cell) {
    for (auto bit : sigmap(sig)) {
      if (bit.wire == nullptr) continue;
      sigusers[bit].insert(cell);
    }
  }

  void blacklist(Cell *cell) {
    if (cell != nullptr && blacklist_cells.insert(cell).second) {
      auto ptr = rollback_cache.find(cell);
      if (ptr == rollback_cache.end()) return;
      int rb = ptr->second;
      if (rollback == 0 || rollback > rb)
        rollback = rb;
    }
  }

  void autoremove(Cell *cell) {
    if (cell != nullptr) {
      autoremove_cells.insert(cell);
      blacklist(cell);
    }
  }

  SigSpec port(Cell *cell, IdString portname) {
    return sigmap(cell->getPort(portname));
  }

  SigSpec port(Cell *cell, IdString portname, const SigSpec& defval) {
    return sigmap(cell->connections_.at(portname, defval));
  }

  Const param(Cell *cell, IdString paramname) {
    return cell->getParam(paramname);
  }

  Const param(Cell *cell, IdString paramname, const Const& defval) {
    return cell->parameters.at(paramname, defval);
  }

  int nusers(const SigSpec &sig) {
    pool<Cell*> users;
    for (auto bit : sigmap(sig))
      for (auto user : sigusers[bit])
        users.insert(user);
    return GetSize(users);
  }

  xilinx_dsp_CREG_pm(Module *module, const vector<Cell*> &cells) :
      module(module), sigmap(module), setup_done(false), generate_mode(false), rngseed(12345678) {
    setup(cells);
  }

  xilinx_dsp_CREG_pm(Module *module) :
      module(module), sigmap(module), setup_done(false), generate_mode(false), rngseed(12345678) {
  }

  void setup(const vector<Cell*> &cells) {
    ud_xilinx_dsp_packC.dff = nullptr;
    ud_xilinx_dsp_packC.dffD = SigSpec();
    ud_xilinx_dsp_packC.dffQ = SigSpec();
    ud_xilinx_dsp_packC.dffcemux = nullptr;
    ud_xilinx_dsp_packC.dffcepol = bool();
    ud_xilinx_dsp_packC.dffclock = SigBit();
    ud_xilinx_dsp_packC.dffrstmux = nullptr;
    ud_xilinx_dsp_packC.dffrstpol = bool();
    ud_xilinx_dsp_packC.unextend = std::function<SigSpec(const SigSpec&)>();
    log_assert(!setup_done);
    setup_done = true;
    for (auto port : module->ports)
      add_siguser(module->wire(port), nullptr);
    for (auto cell : module->cells())
      for (auto &conn : cell->connections())
        add_siguser(conn.second, cell);
    for (auto cell : cells) {
      do {
        Cell *dsp = cell;
        index_0_value_type value;
        std::get<0>(value) = cell;
        if (!(dsp->type.in(id_b_DSP48A, id_b_DSP48A1, id_b_DSP48E1))) continue;
        if (!(param(dsp, id_b_CREG, 1).as_int() == 0)) continue;
        if (!(nusers(port(dsp, id_b_C, SigSpec())) > 1)) continue;
        index_0_key_type key;
        index_0[key].push_back(value);
      } while (0);
      do {
        Cell *ff = cell;
        index_6_value_type value;
        std::get<0>(value) = cell;
        if (!(ff->type.in(id_d_dff))) continue;
        if (!(param(ff, id_b_CLK_POLARITY).as_bool())) continue;
        int &offset = std::get<1>(value);
        for (offset = 0; offset < GetSize(port(ff, id_b_D)); offset++) {
        index_6_key_type key;
        std::get<0>(key) = port(ff, id_b_Q)[offset];
        index_6[key].push_back(value);
        }
      } while (0);
      do {
        Cell *ffrstmux = cell;
        index_8_value_type value;
        std::get<0>(value) = cell;
        if (!(ffrstmux->type.in(id_d_mux))) continue;
        vector<IdString> _pmg_choices_BA = {id_b_B, id_b_A};
        for (const IdString &BA : _pmg_choices_BA) {
        std::get<1>(value) = BA;
        if (!(port(ffrstmux, BA).is_fully_zero())) continue;
        bool &pol = std::get<2>(value);
        pol = (BA == id_b_B);
        index_8_key_type key;
        std::get<0>(key) = port(ffrstmux, id_b_Y);
        index_8[key].push_back(value);
        }
      } while (0);
      do {
        Cell *ffcemux = cell;
        index_10_value_type value;
        std::get<0>(value) = cell;
        if (!(ffcemux->type.in(id_d_mux))) continue;
        vector<IdString> _pmg_choices_AB = {id_b_A, id_b_B};
        for (const IdString &AB : _pmg_choices_AB) {
        std::get<1>(value) = AB;
        bool &pol = std::get<2>(value);
        pol = (AB == id_b_A);
        index_10_key_type key;
        std::get<0>(key) = port(ffcemux, id_b_Y);
        std::get<1>(key) = port(ffcemux, AB);
        index_10[key].push_back(value);
        }
      } while (0);
    }
  }

  ~xilinx_dsp_CREG_pm() {
    for (auto cell : autoremove_cells)
      module->remove(cell);
  }

  int run_xilinx_dsp_packC(std::function<void()> on_accept_f) {
    log_assert(setup_done);
    accept_cnt = 0;
    on_accept = on_accept_f;
    rollback = 0;
    st_xilinx_dsp_packC.argD = SigSpec();
    st_xilinx_dsp_packC.argQ = SigSpec();
    st_xilinx_dsp_packC.clock = SigBit();
    st_xilinx_dsp_packC.dsp = nullptr;
    st_xilinx_dsp_packC.ff = nullptr;
    st_xilinx_dsp_packC.ffC = nullptr;
    st_xilinx_dsp_packC.ffCcemux = nullptr;
    st_xilinx_dsp_packC.ffCcepol = bool();
    st_xilinx_dsp_packC.ffCrstmux = nullptr;
    st_xilinx_dsp_packC.ffCrstpol = bool();
    st_xilinx_dsp_packC.ffcemux = nullptr;
    st_xilinx_dsp_packC.ffcepol = bool();
    st_xilinx_dsp_packC.ffoffset = int();
    st_xilinx_dsp_packC.ffrstmux = nullptr;
    st_xilinx_dsp_packC.ffrstpol = bool();
    st_xilinx_dsp_packC.sigC = SigSpec();
    st_xilinx_dsp_packC.sigP = SigSpec();
    block_0(1);
    log_assert(rollback_cache.empty());
    return accept_cnt;
  }

  int run_xilinx_dsp_packC(std::function<void(xilinx_dsp_CREG_pm&)> on_accept_f) {
    return run_xilinx_dsp_packC([&](){on_accept_f(*this);});
  }

  int run_xilinx_dsp_packC() {
    return run_xilinx_dsp_packC([](){});
  }

  void block_subpattern_xilinx_dsp_packC_(int recursion) { block_0(recursion); }
  void block_subpattern_xilinx_dsp_packC_in_dffe(int recursion) { block_5(recursion); }

  // passes/pmgen/xilinx_dsp_CREG.pmg:43
  void block_0(int recursion YS_ATTRIBUTE(unused)) {
    Cell* &dsp YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.dsp;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;
    Cell* _pmg_backup_dsp = dsp;

    index_0_key_type key;
    auto cells_ptr = index_0.find(key);

    if (cells_ptr != index_0.end()) {
      const vector<index_0_value_type> &cells = cells_ptr->second;
      for (int _pmg_idx = 0; _pmg_idx < GetSize(cells); _pmg_idx++) {
        dsp = std::get<0>(cells[_pmg_idx]);
        if (blacklist_cells.count(dsp)) continue;
        auto rollback_ptr = rollback_cache.insert(make_pair(std::get<0>(cells[_pmg_idx]), recursion));
        block_1(recursion+1);
        if (rollback_ptr.second)
          rollback_cache.erase(rollback_ptr.first);
        if (rollback) {
          if (rollback != recursion) {
            dsp = _pmg_backup_dsp;
            return;
          }
          rollback = 0;
        }
      }
    }

    dsp = nullptr;
    dsp = _pmg_backup_dsp;
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:49
  void block_1(int recursion YS_ATTRIBUTE(unused)) {
    Cell* const &dsp YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.dsp;
    SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    SigSpec &sigC YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.sigC;
    SigSpec &sigP YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.sigP;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;

#define reject do { goto rollback_label; } while(0)
#define accept do { accept_cnt++; on_accept(); if (rollback) goto rollback_label; } while(0)
#define finish do { rollback = -1; goto rollback_label; } while(0)
#define branch do { block_2(recursion+1); if (rollback) goto rollback_label; } while(0)
#define subpattern(pattern_name) do { block_subpattern_xilinx_dsp_packC_ ## pattern_name (recursion+1); if (rollback) goto rollback_label; } while(0)
    unextend = [](const SigSpec &sig) {
      int i;
      for (i = GetSize(sig)-1; i > 0; i--)
        if (sig[i] != sig[i-1])
          break;
      // Do not remove non-const sign bit
      if (sig[i].wire)
        ++i;
      return sig.extract(0, i);
    };
    sigC = unextend(port(dsp, id_b_C, SigSpec()));
    SigSpec P = port(dsp, id_b_P);
    if (!dsp->type.in(id_b_DSP48E1) ||
   param(dsp, id_b_USE_MULT, Const("MULTIPLY")).decode_string() == "MULTIPLY") {
      // Only care about those bits that are used
      int i;
      for (i = GetSize(P)-1; i >= 0; i--)
        if (nusers(P[i]) > 1)
          break;
      i++;
      log_assert(nusers(P.extract_end(i)) <= 1);
      sigP = P.extract(0, i);
    }
    else
      sigP = P;
    clock = port(dsp, id_b_CLK, SigBit());

    block_2(recursion+1);
#undef reject
#undef accept
#undef finish
#undef branch
#undef subpattern

rollback_label:
    YS_ATTRIBUTE(unused);

    clock = SigBit();
    sigC = SigSpec();
    sigP = SigSpec();
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:83
  void block_2(int recursion YS_ATTRIBUTE(unused)) {
    Cell* const &dsp YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.dsp;
    const SigSpec &sigP YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.sigP;
    SigSpec &argQ YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argQ;
    SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    Cell* &ffC YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffC;
    Cell* &ffCcemux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffCcemux;
    bool &ffCcepol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffCcepol;
    Cell* &ffCrstmux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffCrstmux;
    bool &ffCrstpol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffCrstpol;
    SigSpec &sigC YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.sigC;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;

    SigBit _pmg_backup_clock = clock;
    SigSpec _pmg_backup_sigC = sigC;

#define reject do { goto rollback_label; } while(0)
#define accept do { accept_cnt++; on_accept(); if (rollback) goto rollback_label; } while(0)
#define finish do { rollback = -1; goto rollback_label; } while(0)
#define branch do { block_3(recursion+1); if (rollback) goto rollback_label; } while(0)
#define subpattern(pattern_name) do { block_subpattern_xilinx_dsp_packC_ ## pattern_name (recursion+1); if (rollback) goto rollback_label; } while(0)
    argQ = sigC;
    subpattern(in_dffe);
    if (dff) {
      ffC = dff;
      clock = dffclock;
      if (dffrstmux) {
        ffCrstmux = dffrstmux;
        ffCrstpol = dffrstpol;
      }
      if (dffcemux) {
        ffCcemux = dffcemux;
        ffCcepol = dffcepol;
      }
      sigC = dffD;
    }

    block_3(recursion+1);
#undef reject
#undef accept
#undef finish
#undef branch
#undef subpattern

rollback_label:
    YS_ATTRIBUTE(unused);

    clock = _pmg_backup_clock;
    sigC = _pmg_backup_sigC;
    argQ = SigSpec();
    ffC = nullptr;
    ffCcemux = nullptr;
    ffCcepol = bool();
    ffCrstmux = nullptr;
    ffCrstpol = bool();
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:101
  void block_3(int recursion YS_ATTRIBUTE(unused)) {
    const SigSpec &argQ YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argQ;
    const SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    Cell* const &dsp YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.dsp;
    Cell* const &ffC YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffC;
    Cell* const &ffCcemux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffCcemux;
    const bool &ffCcepol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffCcepol;
    Cell* const &ffCrstmux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffCrstmux;
    const bool &ffCrstpol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffCrstpol;
    const SigSpec &sigC YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.sigC;
    const SigSpec &sigP YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.sigP;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;

#define reject do { goto rollback_label; } while(0)
#define accept do { accept_cnt++; on_accept(); if (rollback) goto rollback_label; } while(0)
#define finish do { rollback = -1; goto rollback_label; } while(0)
#define branch do { block_4(recursion+1); if (rollback) goto rollback_label; } while(0)
#define subpattern(pattern_name) do { block_subpattern_xilinx_dsp_packC_ ## pattern_name (recursion+1); if (rollback) goto rollback_label; } while(0)
    if (ffC)
      accept;

    block_4(recursion+1);
#undef reject
#undef accept
#undef finish
#undef branch
#undef subpattern

rollback_label:
    YS_ATTRIBUTE(unused);
  }

  void block_4(int recursion YS_ATTRIBUTE(unused)) {
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:126
  void block_5(int recursion YS_ATTRIBUTE(unused)) {
    const SigSpec &argD YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argD;
    const SigSpec &argQ YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argQ;
    const SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;

#define reject do { goto rollback_label; } while(0)
#define accept do { accept_cnt++; on_accept(); if (rollback) goto rollback_label; } while(0)
#define finish do { rollback = -1; goto rollback_label; } while(0)
#define branch do { block_6(recursion+1); if (rollback) goto rollback_label; } while(0)
#define subpattern(pattern_name) do { block_subpattern_xilinx_dsp_packC_ ## pattern_name (recursion+1); if (rollback) goto rollback_label; } while(0)
    dff = nullptr;
    for (const auto &c : argQ.chunks()) {
      // Abandon matches when 'Q' is a constant
      if (!c.wire)
        reject;
      // Abandon matches when 'Q' has the keep attribute set
      if (c.wire->get_bool_attribute(id_b_keep))
        reject;
      // Abandon matches when 'Q' has a non-zero init attribute set
      // (not supported by DSP48E1)
      Const init = c.wire->attributes.at(id_b_init, Const());
      for (auto b : init.extract(c.offset, c.width))
        if (b != State::Sx && b != State::S0)
          reject;
    }

    block_6(recursion+1);
#undef reject
#undef accept
#undef finish
#undef branch
#undef subpattern

rollback_label:
    YS_ATTRIBUTE(unused);
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:146
  void block_6(int recursion YS_ATTRIBUTE(unused)) {
    const SigSpec &argD YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argD;
    const SigSpec &argQ YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argQ;
    const SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    Cell* &ff YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ff;
    int &ffoffset YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffoffset;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;
    Cell* _pmg_backup_ff = ff;

    index_6_key_type key;
    std::get<0>(key) = argQ[0];
    auto cells_ptr = index_6.find(key);

    if (cells_ptr != index_6.end()) {
      const vector<index_6_value_type> &cells = cells_ptr->second;
      for (int _pmg_idx = 0; _pmg_idx < GetSize(cells); _pmg_idx++) {
        ff = std::get<0>(cells[_pmg_idx]);
        const int &offset YS_ATTRIBUTE(unused) = std::get<1>(cells[_pmg_idx]);
        if (blacklist_cells.count(ff)) continue;
        if (!(GetSize(port(ff, id_b_Q)) >= offset + GetSize(argQ))) continue;
        if (!(port(ff, id_b_Q).extract(offset, GetSize(argQ)) == argQ)) continue;
        if (!(clock == SigBit() || port(ff, id_b_CLK) == clock)) continue;
        auto _pmg_backup_ffoffset = ffoffset;
        ffoffset = offset;
        auto rollback_ptr = rollback_cache.insert(make_pair(std::get<0>(cells[_pmg_idx]), recursion));
        block_7(recursion+1);
        ffoffset = _pmg_backup_ffoffset;
        if (rollback_ptr.second)
          rollback_cache.erase(rollback_ptr.first);
        if (rollback) {
          if (rollback != recursion) {
            ff = _pmg_backup_ff;
            return;
          }
          rollback = 0;
        }
      }
    }

    ff = nullptr;
    ff = _pmg_backup_ff;
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:163
  void block_7(int recursion YS_ATTRIBUTE(unused)) {
    const SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    Cell* const &ff YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ff;
    const int &ffoffset YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffoffset;
    SigSpec &argD YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argD;
    SigSpec &argQ YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argQ;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;

    SigSpec _pmg_backup_argD = argD;
    SigSpec _pmg_backup_argQ = argQ;

#define reject do { goto rollback_label; } while(0)
#define accept do { accept_cnt++; on_accept(); if (rollback) goto rollback_label; } while(0)
#define finish do { rollback = -1; goto rollback_label; } while(0)
#define branch do { block_8(recursion+1); if (rollback) goto rollback_label; } while(0)
#define subpattern(pattern_name) do { block_subpattern_xilinx_dsp_packC_ ## pattern_name (recursion+1); if (rollback) goto rollback_label; } while(0)
    SigSpec Q = port(ff, id_b_Q);
    dff = ff;
    dffclock = port(ff, id_b_CLK);
    dffD = argQ;
    argD = port(ff, id_b_D);
    argQ = Q;
    dffD.replace(argQ, argD);
    // Only search for ffrstmux if dffD only
    //   has two (ff, ffrstmux) users
    if (nusers(dffD) > 2)
      argD = SigSpec();

    block_8(recursion+1);
#undef reject
#undef accept
#undef finish
#undef branch
#undef subpattern

rollback_label:
    YS_ATTRIBUTE(unused);

    argD = _pmg_backup_argD;
    argQ = _pmg_backup_argQ;
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:180
  void block_8(int recursion YS_ATTRIBUTE(unused)) {
    const SigSpec &argD YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argD;
    const SigSpec &argQ YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argQ;
    const SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    Cell* const &ff YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ff;
    const int &ffoffset YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffoffset;
    Cell* &ffrstmux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffrstmux;
    bool &ffrstpol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffrstpol;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;
    Cell* _pmg_backup_ffrstmux = ffrstmux;

    if (!(!argD.empty())) {
      ffrstmux = nullptr;
      block_9(recursion+1);
      ffrstmux = _pmg_backup_ffrstmux;
      return;
    }

    index_8_key_type key;
    std::get<0>(key) = argD;
    auto cells_ptr = index_8.find(key);
    bool found_any_match = false;

    if (cells_ptr != index_8.end()) {
      const vector<index_8_value_type> &cells = cells_ptr->second;
      for (int _pmg_idx = 0; _pmg_idx < GetSize(cells); _pmg_idx++) {
        ffrstmux = std::get<0>(cells[_pmg_idx]);
        const IdString &BA YS_ATTRIBUTE(unused) = std::get<1>(cells[_pmg_idx]);
        const bool &pol YS_ATTRIBUTE(unused) = std::get<2>(cells[_pmg_idx]);
        if (blacklist_cells.count(ffrstmux)) continue;
        found_any_match = true;
        auto _pmg_backup_ffrstpol = ffrstpol;
        ffrstpol = pol;
        auto rollback_ptr = rollback_cache.insert(make_pair(std::get<0>(cells[_pmg_idx]), recursion));
        block_9(recursion+1);
        ffrstpol = _pmg_backup_ffrstpol;
        if (rollback_ptr.second)
          rollback_cache.erase(rollback_ptr.first);
        if (rollback) {
          if (rollback != recursion) {
            ffrstmux = _pmg_backup_ffrstmux;
            return;
          }
          rollback = 0;
        }
      }
    }

    ffrstmux = nullptr;
    if (!found_any_match) block_9(recursion+1);
    ffrstmux = _pmg_backup_ffrstmux;
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:194
  void block_9(int recursion YS_ATTRIBUTE(unused)) {
    const SigSpec &argQ YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argQ;
    const SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    Cell* const &ff YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ff;
    const int &ffoffset YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffoffset;
    Cell* const &ffrstmux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffrstmux;
    const bool &ffrstpol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffrstpol;
    SigSpec &argD YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argD;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;

    SigSpec _pmg_backup_argD = argD;

#define reject do { goto rollback_label; } while(0)
#define accept do { accept_cnt++; on_accept(); if (rollback) goto rollback_label; } while(0)
#define finish do { rollback = -1; goto rollback_label; } while(0)
#define branch do { block_10(recursion+1); if (rollback) goto rollback_label; } while(0)
#define subpattern(pattern_name) do { block_subpattern_xilinx_dsp_packC_ ## pattern_name (recursion+1); if (rollback) goto rollback_label; } while(0)
    if (ffrstmux) {
      dffrstmux = ffrstmux;
      dffrstpol = ffrstpol;
      argD = port(ffrstmux, ffrstpol ? id_b_A : id_b_B);
      dffD.replace(port(ffrstmux, id_b_Y), argD);
      // Only search for ffcemux if argQ has at
      //   least 3 users (ff, <upstream>, ffrstmux) and
      //   dffD only has two (ff, ffrstmux)
      if (!(nusers(argQ) >= 3 && nusers(dffD) == 2))
        argD = SigSpec();
    }
    else
      dffrstmux = nullptr;

    block_10(recursion+1);
#undef reject
#undef accept
#undef finish
#undef branch
#undef subpattern

rollback_label:
    YS_ATTRIBUTE(unused);

    argD = _pmg_backup_argD;
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:215
  void block_10(int recursion YS_ATTRIBUTE(unused)) {
    const SigSpec &argD YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argD;
    const SigSpec &argQ YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argQ;
    const SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    Cell* const &ff YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ff;
    const int &ffoffset YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffoffset;
    Cell* const &ffrstmux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffrstmux;
    const bool &ffrstpol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffrstpol;
    Cell* &ffcemux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffcemux;
    bool &ffcepol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffcepol;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;
    Cell* _pmg_backup_ffcemux = ffcemux;

    if (!(!argD.empty())) {
      ffcemux = nullptr;
      block_11(recursion+1);
      ffcemux = _pmg_backup_ffcemux;
      return;
    }

    index_10_key_type key;
    std::get<0>(key) = argD;
    std::get<1>(key) = argQ;
    auto cells_ptr = index_10.find(key);
    bool found_any_match = false;

    if (cells_ptr != index_10.end()) {
      const vector<index_10_value_type> &cells = cells_ptr->second;
      for (int _pmg_idx = 0; _pmg_idx < GetSize(cells); _pmg_idx++) {
        ffcemux = std::get<0>(cells[_pmg_idx]);
        const IdString &AB YS_ATTRIBUTE(unused) = std::get<1>(cells[_pmg_idx]);
        const bool &pol YS_ATTRIBUTE(unused) = std::get<2>(cells[_pmg_idx]);
        if (blacklist_cells.count(ffcemux)) continue;
        found_any_match = true;
        auto _pmg_backup_ffcepol = ffcepol;
        ffcepol = pol;
        auto rollback_ptr = rollback_cache.insert(make_pair(std::get<0>(cells[_pmg_idx]), recursion));
        block_11(recursion+1);
        ffcepol = _pmg_backup_ffcepol;
        if (rollback_ptr.second)
          rollback_cache.erase(rollback_ptr.first);
        if (rollback) {
          if (rollback != recursion) {
            ffcemux = _pmg_backup_ffcemux;
            return;
          }
          rollback = 0;
        }
      }
    }

    ffcemux = nullptr;
    if (!found_any_match) block_11(recursion+1);
    ffcemux = _pmg_backup_ffcemux;
  }

  // passes/pmgen/xilinx_dsp_CREG.pmg:226
  void block_11(int recursion YS_ATTRIBUTE(unused)) {
    const SigSpec &argQ YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argQ;
    const SigBit &clock YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.clock;
    Cell* const &ff YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ff;
    Cell* const &ffcemux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffcemux;
    const bool &ffcepol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffcepol;
    const int &ffoffset YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffoffset;
    Cell* const &ffrstmux YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffrstmux;
    const bool &ffrstpol YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.ffrstpol;
    SigSpec &argD YS_ATTRIBUTE(unused) = st_xilinx_dsp_packC.argD;
    Cell* &dff YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dff;
    SigSpec &dffD YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffD;
    SigSpec &dffQ YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffQ;
    Cell* &dffcemux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcemux;
    bool &dffcepol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffcepol;
    SigBit &dffclock YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffclock;
    Cell* &dffrstmux YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstmux;
    bool &dffrstpol YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.dffrstpol;
    std::function<SigSpec(const SigSpec&)> &unextend YS_ATTRIBUTE(unused) = ud_xilinx_dsp_packC.unextend;

    SigSpec _pmg_backup_argD = argD;

#define reject do { goto rollback_label; } while(0)
#define accept do { accept_cnt++; on_accept(); if (rollback) goto rollback_label; } while(0)
#define finish do { rollback = -1; goto rollback_label; } while(0)
#define branch do { block_12(recursion+1); if (rollback) goto rollback_label; } while(0)
#define subpattern(pattern_name) do { block_subpattern_xilinx_dsp_packC_ ## pattern_name (recursion+1); if (rollback) goto rollback_label; } while(0)
    if (ffcemux) {
      dffcemux = ffcemux;
      dffcepol = ffcepol;
      argD = port(ffcemux, ffcepol ? id_b_B : id_b_A);
      dffD.replace(port(ffcemux, id_b_Y), argD);
    }
    else
      dffcemux = nullptr;

    block_12(recursion+1);
#undef reject
#undef accept
#undef finish
#undef branch
#undef subpattern

rollback_label:
    YS_ATTRIBUTE(unused);

    argD = _pmg_backup_argD;
  }

  void block_12(int recursion YS_ATTRIBUTE(unused)) {
  }
};
